### ISSUE TITLE
model conversion in tensorrt, UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe8 in position 4: invalid continuation byte

### ISSUE THREAD

**Issue by taoxunqiang** [THU-MIG/yolov10#158]
Hi!
I am trying to use a yolov10n model converted using tensorrt. When I do the following command:
`/TensorRT-8.6.1.6/bin/trtexec  --onnx=yolov10n.onnx --saveEngine=yolov10n.engine --fp16
 yolo predict model=yolov10n.engine`

I get the following error:
`[05/31/2024-09:57:03] [TRT] [I] [MemUsageChange] Init CUDA: CPU +489, GPU +0, now: CPU 602, GPU 500 (MiB)
Traceback (most recent call last):
  File "/software/conda/envs/yolov10/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/src/yolov10/ultralytics/cfg/__init__.py", line 587, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/src/yolov10/ultralytics/engine/model.py", line 434, in predict
    self.predictor.setup_model(model=self.model, verbose=is_cli)
  File "/src/yolov10/ultralytics/engine/predictor.py", line 297, in setup_model
    self.model = AutoBackend(
  File "/software/conda/envs/yolov10/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/src/yolov10/ultralytics/nn/autobackend.py", line 234, in __init__
    metadata = json.loads(f.read(meta_len).decode("utf-8"))  # read metadata
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xec in position 12: invalid continuation byte`

Can someone help me here?

Thanks a lot
Andrea

**Comment by jameslahm** [comment]
Thanks for your interest! Is the engine file correctly exported?

**Comment by jameslahm** [comment]
Please feel free to reopen this issue if you have further questions.

**Comment by Tissum** [comment]
Hi @taoxunqiang ， have you solved this problem? I have also encountered the same problem recently.
