### ISSUE TITLE
Trying to predict

### ISSUE THREAD

**Issue by Meetpatel-09** [THU-MIG/yolov10#175]
(labelImgEnv) C:\Meet\new>yolo task=detect mode=predict model=best.pt show=True conf=0.5 source=w.jpg
Ultralytics YOLOv8.1.34 🚀 Python-3.12.3 torch-2.3.0+cu121 CUDA:0 (NVIDIA GeForce GTX 1650 Ti, 4096MiB)
YOLOv10s summary (fused): 293 layers, 8054310 parameters, 0 gradients, 24.5 GFLOPs

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\pmeet\.conda\envs\labelImgEnv\Scripts\yolo.exe\__main__.py", line 7, in <module>
  File "C:\Users\pmeet\.conda\envs\labelImgEnv\Lib\site-packages\ultralytics\cfg\__init__.py", line 587, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pmeet\.conda\envs\labelImgEnv\Lib\site-packages\ultralytics\engine\model.py", line 443, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pmeet\.conda\envs\labelImgEnv\Lib\site-packages\ultralytics\engine\predictor.py", line 177, in predict_cli
    for _ in gen:  # noqa, running CLI inference without accumulating any outputs (do not modify)
  File "C:\Users\pmeet\.conda\envs\labelImgEnv\Lib\site-packages\torch\utils\_contextlib.py", line 35, in generator_context
    response = gen.send(None)
               ^^^^^^^^^^^^^^
  File "C:\Users\pmeet\.conda\envs\labelImgEnv\Lib\site-packages\ultralytics\engine\predictor.py", line 255, in stream_inference
    self.results = self.postprocess(preds, im, im0s)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pmeet\.conda\envs\labelImgEnv\Lib\site-packages\ultralytics\models\yolo\detect\predict.py", line 25, in postprocess
    preds = ops.non_max_suppression(
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pmeet\.conda\envs\labelImgEnv\Lib\site-packages\ultralytics\utils\ops.py", line 216, in non_max_suppression
    bs = prediction.shape[0]  # batch size
         ^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'shape'

**Comment by 1JayPeng** [comment]
I have the same question,please tell me if you have any answer.

**Comment by 1JayPeng** [comment]
I found the answer. Your model name must be yolov10.pt and cannot be anything else. Alternatively, you can find the YOLO class on line 11 of `ultralytics\models\yolo\model.py` and modify the condition in the __init__ method to force the use of yolov10.

**Comment by jameslahm** [comment]
Thanks for your interest! Does the issue #46 help?

**Comment by Meetpatel-09** [comment]
Thanks @1JayPeng it worked thank you so much

**Comment by jameslahm** [comment]
We just made the YOLOv10 by default in cli. Could you please update the codebase and try again? Thank you!

**Comment by Meetpatel-09** [comment]
solved

**Comment by Meetpatel-09** [comment]
solved

**Comment by Meetpatel-09** [comment]
solved
