### ISSUE TITLE
请问推理速度该怎么测量

### ISSUE THREAD

**Issue by Mingming155** [THU-MIG/yolov10#179]
Speed: 0.2ms preprocess, 4.0ms inference, 0.0ms loss, 0.3ms postprocess per image
Results saved to runs\val\yolov10n
 我使用测试集测了一下 ，推理速度是0.2+4+0.3吗，为什么有后处理的时间

**Comment by jameslahm** [comment]
感谢你的关注！您好，测试推理速度时您可以使用导出的格式进行测试，如onnx，TensorRT engine等。这里的后处理时间是包括根据阈值来筛选预测。

**Comment by Mingming155** [comment]
非常感谢老师您的答疑。我导出onnx之后再val，就报错
Traceback (most recent call last):
  File "E:\xiaolunwen\yolov10-main\yolov10-main\val.py", line 8, in <module>
    model.val(data='dataset/mycoco.yaml',
  File "E:\xiaolunwen\yolov10-main\yolov10-main\ultralytics\engine\model.py", line 518, in val
    validator(model=self.model)
  File "D:\Anaconda\envs\yolo\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "E:\xiaolunwen\yolov10-main\yolov10-main\ultralytics\engine\validator.py", line 187, in __call__
    preds = self.postprocess(preds)
  File "E:\xiaolunwen\yolov10-main\yolov10-main\ultralytics\models\yolov10\val.py", line 18, in postprocess
    boxes, scores, labels = ops.v10postprocess(preds, self.args.max_det, self.nc)
  File "E:\xiaolunwen\yolov10-main\yolov10-main\ultralytics\utils\ops.py", line 852, in v10postprocess
    assert(4 + nc == preds.shape[-1])
AssertionError
 再次感谢您！

**Comment by jameslahm** [comment]
您好，您的代码是最新版本的吗？

**Comment by Mingming155** [comment]
谢谢老师的回复！我用的是前几天的版本，我试过今天下载的版本会出现 
TypeError: YOLOv10.__init_subclass__() takes no keyword arguments这个错误，然后我就用前几天的版本了

**Comment by Mingming155** [comment]
Traceback (most recent call last):
  File "E:\xiaolunwen\yolov10-main (2)\yolov10-main\val.py", line 3, in <module>
    from ultralytics import YOLOv10
  File "E:\xiaolunwen\yolov10-main (2)\yolov10-main\ultralytics\__init__.py", line 5, in <module>
    from ultralytics.data.explorer.explorer import Explorer
  File "E:\xiaolunwen\yolov10-main (2)\yolov10-main\ultralytics\data\explorer\explorer.py", line 18, in <module>
    from ultralytics.models.yolo.model import YOLO
  File "E:\xiaolunwen\yolov10-main (2)\yolov10-main\ultralytics\models\__init__.py", line 6, in <module>
    from .yolov10 import YOLOv10
  File "E:\xiaolunwen\yolov10-main (2)\yolov10-main\ultralytics\models\yolov10\__init__.py", line 1, in <module>
    from .model import YOLOv10
  File "E:\xiaolunwen\yolov10-main (2)\yolov10-main\ultralytics\models\yolov10\model.py", line 9, in <module>
    class YOLOv10(Model, PyTorchModelHubMixin, library_name="ultralytics", repo_url="https://github.com/THU-MIG/yolov10", tags=["object-detection", "yolov10"]):
TypeError: YOLOv10.__init_subclass__() takes no keyword arguments 今天下载的版本model.export成onnx就报这个错

**Comment by Mingming155** [comment]
Class     Images  Instances      Box(P          R      mAP50  mAP50-95):   0%|          | 0/4347 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "E:\xiaolunwen\yolov10-main (2)\yolov10-main\val.py", line 8, in <module>
    model.val(data='dataset/mycoco.yaml',
  File "E:\xiaolunwen\yolov10-main (2)\yolov10-main\ultralytics\engine\model.py", line 516, in val
    validator(model=self.model)
  File "D:\Anaconda\envs\yolo\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "E:\xiaolunwen\yolov10-main (2)\yolov10-main\ultralytics\engine\validator.py", line 187, in __call__
    preds = self.postprocess(preds)
  File "E:\xiaolunwen\yolov10-main (2)\yolov10-main\ultralytics\models\yolov10\val.py", line 18, in postprocess
    boxes, scores, labels = ops.v10postprocess(preds, self.args.max_det, self.nc)
  File "E:\xiaolunwen\yolov10-main (2)\yolov10-main\ultralytics\utils\ops.py", line 852, in v10postprocess
    assert(4 + nc == preds.shape[-1])
AssertionError新版本也出现了这个问题

**Comment by leonnil** [comment]
感谢您提供的信息！我们更新了代码库，请麻烦更新到最新版本再试一下～

**Comment by hopeSerendipity** [comment]
当我将自己训练的模型导出为trt与yolov5训练的模型导出trt对比，发现v10仍然要比v5慢
![8E49180AC753A8FAB6085366BF1609BD](https://github.com/THU-MIG/yolov10/assets/95536210/416a7881-d2a8-48c5-ba03-76e9d81e2fae)
![EBD6B3EBD244FC8E75CECE45229BA272](https://github.com/THU-MIG/yolov10/assets/95536210/93067e22-b0c0-4c81-b28e-b4b499170a0c)
这里的person和bycicle只是显示的问题，实际测试的都是一样的，测试的命令分别是：
v10：yolo predict model=/home/data/hzk/yolo/yolov10/runs/detect/train6/weights/yolov10.engine source=/home/data/hzk/data/yolov10/ClassBehavDataset/yolo_seeCamera/images/val save_txt=True imgsz=1280 save_conf=True
v5：python detect.py --weights runs/train/exp4/weights/best.engine \
    --source /home/data/hzk/data/yolov10/ClassBehavDataset/yolo_seeCamera/images/val \
    --imgsz 1280 \
    --save-txt  \
    --save-conf
