### ISSUE TITLE
RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling cublasSgemv(handle, op, m, n, &alpha, a, lda, x, incx, &beta, y, incy)

### ISSUE THREAD

**Issue by super-song-sir** [THU-MIG/yolov10#209]
当我使用命令 model = YOLOv10('yolov10n.yaml')选定模型后，训练yolov10n.yaml时，进行完一个epoch周期训练再进行验证时会报错CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasSgemv(handle, op, m, n, &alpha, a, lda, x, incx, &beta, y, incy)`。并伴随有警告UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').index = index // nc。但是当我训练yolov10x.yaml时会产生警告，但是并没有出现报错。请问这是什么原因。怎么修复呢？

**Comment by leonnil** [comment]
您好！请问您能给我一些更具体的信息吗（例如，pytorch版本，CUDA版本以及操作系统版本），以及请核查是否正确设置`LD_LIBRARY_PATH`，谢谢！

**Comment by Michealpeng** [comment]
def bbox_decode(self, anchor_points, pred_dist):
        """Decode predicted object bounding box coordinates from anchor points and distribution."""
        if self.use_dfl:
            b, a, c = pred_dist.shape  # batch, anchors, channels
#            pred_dist = pred_dist.view(b, a, 4, c // 4).softmax(3).matmul(self.proj.type(pred_dist.dtype))
            # pred_dist = pred_dist.view(b, a, c // 4, 4).transpose(2,3).softmax(3).matmul(self.proj.type(pred_dist.dtype))
             pred_dist = (pred_dist.view(b, a, c // 4, 4).softmax(2) * self.proj.type(pred_dist.dtype).view(1, 1, -1, 1)).sum(2)
        return dist2bbox(pred_dist, anchor_points, xywh=False)
loss.py种切换下pred_dist就可以了

**Comment by lucameng** [comment]
> def bbox_decode(self, anchor_points, pred_dist): """Decode predicted object bounding box coordinates from anchor points and distribution.""" if self.use_dfl: b, a, c = pred_dist.shape # batch, anchors, channels
> # pred_dist = pred_dist.view(b, a, 4, c // 4).softmax(3).matmul(self.proj.type(pred_dist.dtype))
> 
> ```
>         # pred_dist = pred_dist.view(b, a, c // 4, 4).transpose(2,3).softmax(3).matmul(self.proj.type(pred_dist.dtype))
>          pred_dist = (pred_dist.view(b, a, c // 4, 4).softmax(2) * self.proj.type(pred_dist.dtype).view(1, 1, -1, 1)).sum(2)
>     return dist2bbox(pred_dist, anchor_points, xywh=False)
> ```
> 
> loss.py种切换下pred_dist就可以了

尝试了还是不行

**Comment by tangxiu1110** [comment]
New https://pypi.org/project/ultralytics/8.3.13 available 😃 Update with 'pip install -U ultralytics'
Ultralytics YOLOv8.1.34 🚀 Python-3.9.20 torch-1.12.1 CUDA:0 (NVIDIA GeForce RTX 4060 Ti, 16380MiB)
WARNING ⚠️ Upgrade to torch>=2.0.0 for deterministic training.
engine\trainer: task=detect, mode=train, model=yolov10n.pt, data=D:\yolov10\yolov10-main\data\car_fire\data.yaml, epochs=200, time=None, patience=100, batch=16, imgsz=640, save=True, save_period=-1, val_period=1, cache=False, device=None, workers=8, project=None, name=train9, exist_ok=False, pretrained=False, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, bgr=0.0, mosaic=1.0, mixup=0.0, copy_paste=0.0, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=None, tracker=botsort.yaml, save_dir=runs\detect\train9
Overriding model.yaml nc=80 with nc=1
train: Scanning D:\yolov10\yolov10-main\data\car_fire\train\labels.cache... 4950 images, 0 backgrounds, 0 corrupt: 100%|██████████| 4950/4950 [00:00<?, ?it/s]
val: Scanning D:\yolov10\yolov10-main\data\car_fire\valid\labels.cache... 550 images, 0 backgrounds, 0 corrupt: 100%|██████████| 550/550 [00:00<?, ?it/s]
Plotting labels to runs\detect\train9\labels.jpg... 
  0%|          | 0/310 [00:00<?, ?it/s]optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically... 
optimizer: SGD(lr=0.01, momentum=0.9) with parameter groups 95 weight(decay=0.0), 108 weight(decay=0.0005), 107 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to runs\detect\train9
Starting training for 200 epochs...

      Epoch    GPU_mem     box_om     cls_om     dfl_om     box_oo     cls_oo     dfl_oo  Instances       Size
      1/200       3.1G       1.42      2.535      1.529      1.244      5.526      1.378         17        640: 100%|██████████| 310/310 [00:53<00:00,  5.78it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95):   0%|          | 0/18 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "D:\yolov10\yolov10-main\cs.py", line 16, in <module>
    model.train(data='D:\yolov10\yolov10-main\data\car_fire\data.yaml', epochs=200, batch=16, imgsz=640) #这里写训练参数位置
  File "D:\yolov10\yolov10-main\ultralytics\engine\model.py", line 657, in train
    self.trainer.train()
  File "D:\yolov10\yolov10-main\ultralytics\engine\trainer.py", line 213, in train
    self._do_train(world_size)
  File "D:\yolov10\yolov10-main\ultralytics\engine\trainer.py", line 430, in _do_train
    self.metrics, self.fitness = self.validate()
  File "D:\yolov10\yolov10-main\ultralytics\engine\trainer.py", line 552, in validate
    metrics = self.validator(self)
  File "D:\Anaconda\envs\yolo10\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\yolov10\yolov10-main\ultralytics\engine\validator.py", line 183, in __call__
    self.loss += model.loss(batch, preds)[1]
  File "D:\yolov10\yolov10-main\ultralytics\nn\tasks.py", line 275, in loss
    return self.criterion(preds, batch)
  File "D:\yolov10\yolov10-main\ultralytics\utils\loss.py", line 724, in __call__
    loss_one2many = self.one2many(one2many, batch)
  File "D:\yolov10\yolov10-main\ultralytics\utils\loss.py", line 219, in __call__
    pred_bboxes = self.bbox_decode(anchor_points, pred_distri)  # xyxy, (b, h*w, 4)
  File "D:\yolov10\yolov10-main\ultralytics\utils\loss.py", line 191, in bbox_decode
    pred_dist = pred_dist.view(b, a, 4, c // 4).softmax(3).matmul(self.proj.type(pred_dist.dtype))
RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasSgemv(handle, op, m, n, &alpha, a, lda, x, incx, &beta, y, incy)`
我也是同样的错误，不知道为什么，还是不行

**Comment by Yipzcc** [comment]
可以通过分割concat的思想解决，这一般是因为矩阵乘法运算时暴显存了
```
        if self.use_dfl:
            b, a, c = pred_dist.shape  # batch, anchors, channels
            # pred_dist = pred_dist.view(b, a, 4, c // 4).softmax(3).matmul(self.proj.type(pred_dist.dtype))
            # pred_dist = pred_dist.view(b, a, c // 4, 4).transpose(2,3).softmax(3).matmul(self.proj.type(pred_dist.dtype))
            # pred_dist = (pred_dist.view(b, a, c // 4, 4).softmax(2) * self.proj.type(pred_dist.dtype).view(1, 1, -1, 1)).sum(2)
            'yzc'
            pred_distsoft = pred_dist.view(b, a, 4, c // 4).softmax(3)
            pred_dist1 = pred_distsoft[:,:int(a/4),:,:].matmul(self.proj.type(pred_dist.dtype))
            pred_dist2 = pred_distsoft[:,int(a/4):int(2*a/4),:,:].matmul(self.proj.type(pred_dist.dtype))
            pred_dist3 = pred_distsoft[:,int(2*a/4):int(3*a/4),:,:].matmul(self.proj.type(pred_dist.dtype))
            pred_dist4 = pred_distsoft[:,int(3*a/4):,:,:].matmul(self.proj.type(pred_dist.dtype))
            pred_dist = torch.cat([pred_dist1, pred_dist2,pred_dist3,pred_dist4], dim=1)
```

**Comment by llhh667** [comment]
root/.virtualenvs/magic/bin/python /tmp/yolo11magic/ultralytics-8.3.12/train_2.py 
/usr/local/miniconda3/envs/v11/lib/python3.10/site-packages/timm/models/layers/__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
WARNING ⚠️ no model scale passed. Assuming scale='n'.
Ultralytics 8.3.12 🚀 Python-3.10.14 torch-1.12.1 CUDA:0 (NVIDIA GeForce RTX 3090, 24260MiB)
WARNING ⚠️ Upgrade to torch>=2.0.0 for deterministic training.
engine/trainer: task=detect, mode=train, model=/tmp/yolo11magic/ultralytics-8.3.12/ultralytics/cfg/models/v8/yolov8.yaml, data=/hy-tmp/data.yaml, epochs=300, time=None, patience=50, batch=16, imgsz=640, save=True, save_period=-1, cache=False, device=0, workers=8, project=runs/train, name=expv8m3, exist_ok=False, pretrained=False, optimizer=SGD, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=True, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, bgr=0.0, mosaic=1.0, mixup=0.0, copy_paste=0.0, copy_paste_mode=flip, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=None, tracker=botsort.yaml, save_dir=runs/train/expv8m3
WARNING ⚠️ no model scale passed. Assuming scale='n'.

                   from  n    params  module                                       arguments                     
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]                 
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]                
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]             
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]                
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]             
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]               
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]           
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]              
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]           
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]                 
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]                 
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]                  
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]                
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]                 
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]              
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]                 
 22        [15, 18, 21]  1    432037  ultralytics.nn.modules.head.Detect           [7, [64, 128, 256]]           
YOLOv8 summary: 249 layers, 2,691,573 parameters, 2,691,557 gradients, 6.9 GFLOPs

Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks with YOLO11n...
AMP: checks passed ✅
train: Scanning /hy-tmp/train/labels.cache... 3573 images, 0 backgrounds, 0 corr
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, num_output_channels=3, method='weighted_average'), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Scanning /hy-tmp/valid/labels.cache... 446 images, 0 backgrounds, 0 corrupt
Plotting labels to runs/train/expv8m3/labels.jpg... 
optimizer: SGD(lr=0.01, momentum=0.937) with parameter groups 63 weight(decay=0.0), 70 weight(decay=0.0005), 69 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to runs/train/expv8m3
Starting training for 300 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
  0%|          | 0/224 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/tmp/yolo11magic/ultralytics-8.3.12/train_2.py", line 8, in <module>
    model.train(
  File "/tmp/yolo11magic/ultralytics-8.3.12/ultralytics/engine/model.py", line 802, in train
    self.trainer.train()
  File "/tmp/yolo11magic/ultralytics-8.3.12/ultralytics/engine/trainer.py", line 207, in train
    self._do_train(world_size)
  File "/tmp/yolo11magic/ultralytics-8.3.12/ultralytics/engine/trainer.py", line 393, in _do_train
    self.scaler.scale(self.loss).backward()
  File "/usr/local/miniconda3/envs/v11/lib/python3.10/site-packages/torch/_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/usr/local/miniconda3/envs/v11/lib/python3.10/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Function 'ConvolutionBackward0' returned nan values in its 1th output.

**Comment by LSZ-03** [comment]
I also encountered a similar issue. The root cause was GPU memory overflow, and a simple solution is to reduce the batch size.

**Comment by 1105128053** [comment]
> 新的https://pypi.org/project/ultralytics/8.3.13可用 😃 使用“pip install -U ultralytics”更新 Ultralytics YOLOv8.1.34 🚀 Python-3.9.20 torch-1.12.1 CUDA:0（NVIDIA GeForce RTX 4060 Ti，16380MiB） 警告⚠️升级到 torch>=2.0.0 进行确定性训练。 引擎\训练器：任务=检测，模式=训练，模型=yolov10n.pt，数据=D：\ yolov10 \ yolov10-main \ data \ car_fire \ data.yaml，epochs = 200，时间=无，耐心=100，批次=16，imgsz = 640，保存= True，save_period = -1，val_period = 1，缓存= False，设备=无，工人=8，项目=无，名称= train9，exist_ok = False，预训练= False，优化器=自动，详细= True，种子= 0，确定性= True，single_cls = False，rect = False，cos_lr = False，close_mosaic = 10，简历= False，amp = True，分数= 1.0，配置文件= False，冻结=无，多尺度= False，重叠掩码= True，mask_ratio = 4，dropout = 0.0， val=True，split=val，save_json=False，save_hybrid=False，conf=None，iou=0.7，max_det=300，half=False，dnn=False，plots=True，source=None，vid_stride=1，stream_buffer=False，visualize=False，augment=False，agnostic_nms=False，classes=None，retina_masks=False，embed=None，show=False，save_frames=False，save_txt=False，save_conf=False，save_crop=False，show_labels=True，show_conf=True，show_boxes=True，line_width=None，format=torchscript，keras=False，optimize=False，int8=False，dynamic=False，simplify=False，opset=None，workspace=4，nms=False，lr0=0.01，lrf=0.01，动量=0.937，weight_decay=0.0005，warmup_epochs=3.0，warmup_momentum=0.8，warmup_bias_lr=0.1，box=7.5，cls=0.5，dfl=1.5，pose=12.0，kobj=1.0，label_smoothing=0.0，nbs=64，hsv_h=0.015，hsv_s=0.7，hsv_v=0.4，度=0.0，平移=0.1，比例=0.5，剪切=0.0，透视=0.0，flipud=0.0，fliplr=0.5，bgr=0.0，马赛克=1.0，混合=0.0，copy_paste=0.0，auto_augment=randaugment，擦除=0.4，crop_fraction=1.0， cfg=None，tracker=botsort.yaml，save_dir=runs\detect\train9 用 nc=1 覆盖 model.yaml nc=80 训练：扫描 D:\yolov10\yolov10-main\data\car_fire\train\labels.cache... 4950 张图片，0 张背景，0 个损坏：100%|██████████| 4950/4950 [00:00<?, ?it/s] val：扫描 D:\yolov10\yolov10-main\data\car_fire\valid\labels.cache... 550 张图片，0 张背景，0 个损坏：100%|██████████| 550/550 [00:00<?, ?it/s] 将标签绘制到 runs\detect\train9\labels.jpg... 0%| | 0/310 [00:00<?, ?it/s]优化器：发现“optimizer=auto”，忽略“lr0=0.01”和“momentum=0.937”，自动确定最佳“optimizer”、“lr0”和“momentum”... 优化器：SGD(lr=0.01, momentum=0.9)，参数组为 95 weight(decay=0.0)、108 weight(decay=0.0005)、107 bias(decay=0.0)， 图像大小为 640 train，640 val， 使用 8 个数据加载器工作者， 将结果记录到 runs\detect\train9， 开始训练 200 个时期...
> 
> ```
>   Epoch    GPU_mem     box_om     cls_om     dfl_om     box_oo     cls_oo     dfl_oo  Instances       Size
>   1/200       3.1G       1.42      2.535      1.529      1.244      5.526      1.378         17        640: 100%|██████████| 310/310 [00:53<00:00,  5.78it/s]
>              Class     Images  Instances      Box(P          R      mAP50  mAP50-95):   0%|          | 0/18 [00:00<?, ?it/s]
> ```
> 
> Traceback (most recent call last): File "D:\yolov10\yolov10-main\cs.py", line 16, in model.train(data='D:\yolov10\yolov10-main\data\car_fire\data.yaml', epochs=200, batch=16, imgsz=640) #这里写训练参数位置 File "D:\yolov10\yolov10-main\ultralytics\engine\model.py", line 657, in train self.trainer.train() File "D:\yolov10\yolov10-main\ultralytics\engine\trainer.py", line 213, in train self._do_train(world_size) File "D:\yolov10\yolov10-main\ultralytics\engine\trainer.py", line 430, in _do_train self.metrics, self.fitness = self.validate() File "D:\yolov10\yolov10-main\ultralytics\engine\trainer.py", line 552, in validate metrics = self.validator(self) File "D:\Anaconda\envs\yolo10\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context return func(_args, **kwargs) File "D:\yolov10\yolov10-main\ultralytics\engine\validator.py", line 183, in **call** self.loss += model.loss(batch, preds)[1] File "D:\yolov10\yolov10-main\ultralytics\nn\tasks.py", line 275, in loss return self.criterion(preds, batch) File "D:\yolov10\yolov10-main\ultralytics\utils\loss.py", line 724, in **call** loss_one2many = self.one2many(one2many, batch) File "D:\yolov10\yolov10-main\ultralytics\utils\loss.py", line 219, in **call** pred_bboxes = self.bbox_decode(anchor_points, pred_distri) # xyxy, (b, h_w, 4) File "D:\yolov10\yolov10-main\ultralytics\utils\loss.py", line 191, in bbox_decode pred_dist = pred_dist.view(b, a, 4, c // 4).softmax(3).matmul(self.proj.type(pred_dist.dtype)) RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasSgemv(handle, op, m, n, &alpha, a, lda, x, incx, &beta, y, incy)` 我也是同样的错误，不知道为什么，还是不行

可以试试把batch调小一点，我是将batch从16改成8就不出现这个问题了
