### ISSUE TITLE
Prediction throwing error

### ISSUE THREAD

**Issue by rokkamaravind321** [THU-MIG/yolov10#220]
I tried run my custom trained yolov10 model using "yolo detect predict model=runs/detect/train2/weights/best.pt source=data-master/test-pics/test1.jpg"

im getting this error -

Traceback (most recent call last):
  File "/home/isaac/anaconda3/envs/yolov10/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/isaac/conda_envs/yolov10/ultralytics/cfg/__init__.py", line 587, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/home/isaac/conda_envs/yolov10/ultralytics/engine/model.py", line 441, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "/home/isaac/conda_envs/yolov10/ultralytics/engine/predictor.py", line 177, in predict_cli
    for _ in gen:  # noqa, running CLI inference without accumulating any outputs (do not modify)
  File "/home/isaac/anaconda3/envs/yolov10/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/home/isaac/conda_envs/yolov10/ultralytics/engine/predictor.py", line 255, in stream_inference
    self.results = self.postprocess(preds, im, im0s)
  File "/home/isaac/conda_envs/yolov10/ultralytics/models/yolo/detect/predict.py", line 25, in postprocess
    preds = ops.non_max_suppression(
  File "/home/isaac/conda_envs/yolov10/ultralytics/utils/ops.py", line 216, in non_max_suppression
    bs = prediction.shape[0]  # batch size
AttributeError: 'dict' object has no attribute 'shape'

How do i solve this?

**Comment by leonnil** [comment]
Thanks for your interest! Does the issue https://github.com/THU-MIG/yolov10/issues/46 help?
