### ISSUE TITLE
bs = prediction.shape[0]  # batch size  AttributeError: 'dict' object has no attribute 'shape

### ISSUE THREAD

**Issue by boltholds** [THU-MIG/yolov10#258]
I can't run YOLOv10 on RPI4
Install  from pip install -e .

libs versions:
ultralytics 8.1.34
torch        2.2.2
huggingface_hub   0.23.3

Traceback (most recent call last):
  File "/opt/vrai/recognizer.py", line 248, in <module>
    detect_objects(args.image_path_dm, args.output_file, args.image_path_dr)
  File "/opt/vrai/recognizer.py", line 188, in detect_objects
    results_dr = model_dr.predict(crop_img_dr, conf=model_dr_conf, iou=model_dr_iou, half=half_precesion)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/vrai/yolov10/ultralytics/engine/model.py", line 441, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/vrai/yolov10/ultralytics/engine/predictor.py", line 168, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/vrai/venv/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
               ^^^^^^^^^^^^^^
  File "/opt/vrai/yolov10/ultralytics/engine/predictor.py", line 255, in stream_inference
    self.results = self.postprocess(preds, im, im0s)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/vrai/yolov10/ultralytics/models/yolo/detect/predict.py", line 25, in postprocess
    preds = ops.non_max_suppression(
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/vrai/yolov10/ultralytics/utils/ops.py", line 216, in non_max_suppression
    bs = prediction.shape[0]  # batch size
         ^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'shape

 print(type(prediction)) return in cmd <class 'torch.Tensor'> i don't understand

**Comment by boltholds** [comment]
> I can't run YOLOv10 on RPI4 Install from pip install -e .
> 
> libs versions: ultralytics 8.1.34 torch 2.2.2 huggingface_hub 0.23.3
> 
> Traceback (most recent call last): File "/opt/vrai/recognizer.py", line 248, in detect_objects(args.image_path_dm, args.output_file, args.image_path_dr) File "/opt/vrai/recognizer.py", line 188, in detect_objects results_dr = model_dr.predict(crop_img_dr, conf=model_dr_conf, iou=model_dr_iou, half=half_precesion) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/opt/vrai/yolov10/ultralytics/engine/model.py", line 441, in predict return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/opt/vrai/yolov10/ultralytics/engine/predictor.py", line 168, in **call** return list(self.stream_inference(source, model, *args, **kwargs)) # merge list of Result into one ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/opt/vrai/venv/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 35, in generator_context response = gen.send(None) ^^^^^^^^^^^^^^ File "/opt/vrai/yolov10/ultralytics/engine/predictor.py", line 255, in stream_inference self.results = self.postprocess(preds, im, im0s) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/opt/vrai/yolov10/ultralytics/models/yolo/detect/predict.py", line 25, in postprocess preds = ops.non_max_suppression( ^^^^^^^^^^^^^^^^^^^^^^^^ File "/opt/vrai/yolov10/ultralytics/utils/ops.py", line 216, in non_max_suppression bs = prediction.shape[0] # batch size ^^^^^^^^^^^^^^^^ AttributeError: 'dict' object has no attribute 'shape
> 
> print(type(prediction)) return in cmd <class 'torch.Tensor'> i don't understand

i Fix It!
from ultralytics import YOLOv10 as YOLO
