### ISSUE TITLE
in app.py detect a video, finally has some error

### ISSUE THREAD

**Issue by Zha-Miku** [THU-MIG/yolov10#265]
Completely in accordance with the requirements of the configuration of the environment, reasoning when using each model picture is normal, but when change to the video has the errors

```
Traceback (most recent call last):
  File "C:\Users\20116\anaconda3\envs\yolov10\lib\site-packages\ffmpy.py", line 95, in run
    self.process = subprocess.Popen(
  File "C:\Users\20116\anaconda3\envs\yolov10\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\20116\anaconda3\envs\yolov10\lib\subprocess.py", line 1436, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\20116\anaconda3\envs\yolov10\lib\site-packages\gradio\queueing.py", line 528, in process_events
    response = await route_utils.call_process_api(
  File "C:\Users\20116\anaconda3\envs\yolov10\lib\site-packages\gradio\route_utils.py", line 270, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\20116\anaconda3\envs\yolov10\lib\site-packages\gradio\blocks.py", line 1918, in process_api
    data = await self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\20116\anaconda3\envs\yolov10\lib\site-packages\gradio\blocks.py", line 1744, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "C:\Users\20116\anaconda3\envs\yolov10\lib\site-packages\gradio\components\video.py", line 242, in postprocess
    processed_files = (self._format_video(value), None)
  File "C:\Users\20116\anaconda3\envs\yolov10\lib\site-packages\gradio\components\video.py", line 295, in _format_video        
    and not processing_utils.video_is_playable(video)
  File "C:\Users\20116\anaconda3\envs\yolov10\lib\site-packages\gradio\processing_utils.py", line 923, in video_is_playable    
    output = probe.run(stderr=subprocess.PIPE, stdout=subprocess.PIPE)
  File "C:\Users\20116\anaconda3\envs\yolov10\lib\site-packages\ffmpy.py", line 105, in run
    raise FFExecutableNotFoundError(
ffmpy.FFExecutableNotFoundError: Executable 'ffprobe' not found
```

<details><summary>Settin Details</summary>
<p>

![image](https://github.com/THU-MIG/yolov10/assets/54501325/e5a12953-6929-4a9e-ae12-8d1fe0dd480d)

</p>
</details> 

<details><summary>Src Details</summary>
<p>

(base) PS C:\Users\20116\Videos\Game.exe> ffmpeg -i .\1_60-.mp4
ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9.2.1 (GCC) 20200122
  configuration: --disable-static --enable-shared --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '.\1_60-.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    date            : 2024
    encoder         : Lavf58.29.100
  Duration: 00:00:10.13, start: 0.020000, bitrate: 9322 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, smpte170m), 1920x1080 [SAR 1:1 DAR 16:9], 9479 kb/s, 59.80 fps, 60 tbr, 90k tbn, 120 tbc (default)
    Metadata:
      handler_name    : VideoHandle
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 195 kb/s (default)
    Metadata:
      handler_name    : SoundHandle
At least one output file must be specified
(base) PS C:\Users\20116\Videos\Game.exe>

</p>
</details> 

<details><summary>My Env Details</summary>
<p>

(yolov10) PS E:\Prjs\AI\Yolo_v10> python C:\Users\20116\anaconda3\envs\yolov10\Lib\site-packages\torch\utils\collect_env.py    
Collecting environment information...
PyTorch version: 2.0.1+cpu
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 家庭中文版
GCC version: (x86_64-win32-sjlj-rev0, Built by MinGW-W64 project) 8.1.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.19 (main, May  6 2024, 20:12:36) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22000-SP0
Is CUDA available: False
CUDA runtime version: 11.7.64
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3050 Laptop GPU
Nvidia driver version: 537.58
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\bin\cudnn_ops_train64_8.dll
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=2700
DeviceID=CPU0
Family=198
L2CacheSize=10240
L2CacheSpeed=
Manufacturer=GenuineIntel
MaxClockSpeed=2700
Name=12th Gen Intel(R) Core(TM) i7-12700H
ProcessorType=3
Revision=

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] torch==2.0.1
[pip3] torchvision==0.15.2
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] torch                     2.0.1                    pypi_0    pypi
[conda] torchvision               0.15.2                   pypi_0    pypi

</p>
</details>

**Comment by Zha-Miku** [comment]
Probably built without the EXE

![image](https://github.com/THU-MIG/yolov10/assets/54501325/6f381c07-bd88-4069-8755-d5c4f5cc4c35)

without errors

```
0: 384x640 1 person, 118.0ms
Speed: 3.0ms preprocess, 118.0ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)
C:\Users\20116\anaconda3\envs\yolov10\lib\site-packages\gradio\components\video.py:297: UserWarning: Video does not have browser-compatible container or codec. Converting to mp4
  warnings.warn(

```

why built without *\yolov10\Library\bin\ffprobe.exe ?
