### ISSUE TITLE
run "python app.py" error

### ISSUE THREAD

**Issue by lifw555** [THU-MIG/yolov10#302]
```
$ /data/yolov10 python app.py 
Will cache examples in '/data/yolov10/gradio_cached_examples/19' directory at first use. 


Running on local URL:  http://127.0.0.1:7860
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_backends/sync.py", line 126, in read
    return self._sock.recv(max_bytes)
TimeoutError: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 66, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 228, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection_pool.py", line 268, in handle_request
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection_pool.py", line 251, in handle_request
    response = connection.handle_request(request)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/http_proxy.py", line 207, in handle_request
    return self._connection.handle_request(proxy_request)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection.py", line 103, in handle_request
    return self._connection.handle_request(request)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/http11.py", line 133, in handle_request
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/http11.py", line 111, in handle_request
    ) = self._receive_response_headers(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/http11.py", line 176, in _receive_response_headers
    event = self._receive_event(timeout=timeout)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/http11.py", line 212, in _receive_event
    data = self._network_stream.read(
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_backends/sync.py", line 124, in read
    with map_exceptions(exc_map):
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ReadTimeout: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/yolov10/app.py", line 161, in <module>
    gradio_app.launch()
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 2372, in launch
    and not networking.url_ok(self.local_url)
  File "/usr/local/lib/python3.10/dist-packages/gradio/networking.py", line 54, in url_ok
    r = httpx.head(url, timeout=3, verify=False)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_api.py", line 265, in head
    return request(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_api.py", line 100, in request
    return client.request(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 814, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 901, in send
    response = self._send_handling_auth(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 929, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 966, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 1002, in _send_single_request
    response = transport.handle_request(request)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 227, in handle_request
    with map_httpcore_exceptions():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 83, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadTimeout: timed out

```

**Comment by senceryucel** [comment]
Hey, @lifw555 
Check your firewall rules. It might be blocking the port 7860.

For Linux:
```sudo ufw status``` 
```sudo ufw allow 7860```

For Windows:
https://answers.microsoft.com/en-us/windows/forum/all/how-to-open-port-in-windows-10-firewall/f38f67c8-23e8-459d-9552-c1b94cca579a

If this does not work, try to change the port of the app by changing the very last line of app.py:
```gradio_app.launch(server_port=3000)```
and then retry to reach it from http://127.0.0.1:3000/

If this also does not work, please let me know and we'll find another approach together.

**Comment by lifw555** [comment]
ths
