### ISSUE TITLE
SavedModel file does not exist

### ISSUE THREAD

**Issue by Narek-939** [THU-MIG/yolov10#331]
I have got this error runing this command

yolo export model=.../weights/best.pt format=edgetpu imgsz=320 data=.../data.yaml

TensorFlow SavedModel: export failure ❌ 41.1s: SavedModel file does not exist at: /.../weights/best_saved_model/{saved_model.pbtxt|saved_model.pb}
Traceback (most recent call last):
  File ".../yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/vin/.local/lib/python3.10/site-packages/ultralytics/cfg/__init__.py", line 697, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/home/vin/.local/lib/python3.10/site-packages/ultralytics/engine/model.py", line 591, in export
    return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)
  File "/home/vin/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/vin/.local/lib/python3.10/site-packages/ultralytics/engine/exporter.py", line 313, in __call__
    f[5], keras_model = self.export_saved_model()
  File "/home/vin/.local/lib/python3.10/site-packages/ultralytics/engine/exporter.py", line 142, in outer_func
    raise e
  File "/home/vin/.local/lib/python3.10/site-packages/ultralytics/engine/exporter.py", line 137, in outer_func
    f, model = inner_func(*args, **kwargs)
  File "/home/vin/.local/lib/python3.10/site-packages/ultralytics/engine/exporter.py", line 879, in export_saved_model
    onnx2tf.convert(
  File "/home/vin/.local/lib/python3.10/site-packages/onnx2tf/onnx2tf.py", line 1394, in convert
    loaded_saved_model = tf.saved_model.load(
  File "/home/vin/.local/lib/python3.10/site-packages/tensorflow/python/saved_model/load.py", line 912, in load
    result = load_partial(export_dir, None, tags, options)["root"]
  File "/home/vin/.local/lib/python3.10/site-packages/tensorflow/python/saved_model/load.py", line 1016, in load_partial
    loader_impl.parse_saved_model_with_debug_info(export_dir))
  File "/home/vin/.local/lib/python3.10/site-packages/tensorflow/python/saved_model/loader_impl.py", line 59, in parse_saved_model_with_debug_info
    saved_model = parse_saved_model(export_dir)
  File "/home/vin/.local/lib/python3.10/site-packages/tensorflow/python/saved_model/loader_impl.py", line 119, in parse_saved_model
    raise IOError(
OSError: SavedModel file does not exist at: .../weights/best_saved_model/{saved_model.pbtxt|saved_model.pb}

**Comment by canadarob** [comment]
you have to disable group convolution within the onn2tf configuration. I had to modify the exporter.py

**Comment by Narek-939** [comment]
@canadarob please can you share your modifications?

**Comment by mwkldeveloper** [comment]
@Narek-939 https://github.com/PINTO0309/onnx2tf/issues/629

in exporter.py You can find a func `onnx2tf.convert(..........)`
just add `disable_group_convolution=True`

**Comment by skyler9901** [comment]
> you have to disable group convolution within the onn2tf configuration. I had to modify the exporter.py

could you tell me why the group convolution should be disabled within the onn2tf configuration?
