### ISSUE TITLE
Unable to start basic training with pretrained coco weights, KeyError: 'epoch'.

### ISSUE THREAD

**Issue by alaap001** [THU-MIG/yolov10#41]
Hey, thanks for the repo. 
I wanted to train coco on 1280 and set my python train file like this:

```
from ultralytics import YOLOv10

model = YOLOv10(f'yolov10x.pt')

results = model.train(data='coco.yaml', epochs=120, imgsz=1280, device=[0, 1, 2, 3], 
                      batch=16, close_mosaic=20, project='coco-1280', resume=False)

```
this should start standard training of coco with 1280 imgsz from pretrained weight file of 640 imgsz.
However, when I try to load model like this I get:
```

Traceback (most recent call last):                                                                                                                                                                                  
  File "/home/.config/Ultralytics/DDP/_temp_asyw3_vx140544015144176.py", line 12, in <module>                                                                                                                 
    results = trainer.train()                                                                                                                                                                                       
  File "/home/anaconda3/envs/yolov10/lib/python3.9/site-packages/ultralytics/engine/trainer.py", line 213, in train                                                                                           
    self._do_train(world_size)                                                                                                                                                                                      
  File "/home/anaconda3/envs/yolov10/lib/python3.9/site-packages/ultralytics/engine/trainer.py", line 327, in _do_train                                                                                       
    self._setup_train(world_size)                                                                                                                                                                                   
  File "/home/anaconda3/envs/yolov10/lib/python3.9/site-packages/ultralytics/engine/trainer.py", line 319, in _setup_train                                                                                    
    self.resume_training(ckpt)                                                                                                                                                                                      
  File "/home/anaconda3/envs/yolov10/lib/python3.9/site-packages/ultralytics/engine/trainer.py", line 665, in resume_training                                                                                 
    start_epoch = ckpt["epoch"] + 1                                                                                                                                                                                 
KeyError: 'epoch'  
```

for some reason it is trying to resume even when it should not.

**Comment by jameslahm** [comment]
Thanks for your interest! It seems like a bug in ultralytics. A fix is to use `python -m torch.distributed.run --nproc_per_node 4 train.py` to launch it. Could you please try it?

**Comment by alaap001** [comment]
yeah it worked, it's a strange fix tbh. Seems like some dis check is failing leading to this. I never faced it while training v8, I'll try to look into it deeper and send a pull request if found a fix for the bug. 
Thanks for the help.

**Comment by tfriedel** [comment]
I have the same error, but when running something like
```
yolo detect train data=coco.yaml model=yolov10n.pt epochs=30 batch=64 imgsz=640 device=0,1,2,3
```
