### ISSUE TITLE
Plance无法解析导入yolov10但是可以正常运行代码 打包后出现Traceback (most recent call last):   File "TRITIUM.py", line 72, in <module> ImportError: cannot import name 'YOLOv10' from 'ultralytics' (F:\1PyProject\..._internal\ultralytics\__init__.pyc)

### ISSUE THREAD

**Issue by Zi-kiki** [THU-MIG/yolov10#413]
直接用解释器运行代码一切都正常运行 使用pyinstaller打包后出现了Traceback (most recent call last):   File "TRITIUM.py", line 72, in <module> ImportError: cannot import name 'YOLOv10' from 'ultralytics' (F:\1PyProject\..._internal\ultralytics\__init__.pyc) 我已经将所有的模块都复制到了_internal

**Comment by Zi-kiki** [comment]
尝试网上各种方法后最终遇到的错误为ValueError: Could not find the operator torchvision::nms. Please make sure you have already registered the operator and (if registered from C++) loaded it via torch.ops.load_library. 无论在如何操作始终为此错误
