### ISSUE TITLE
Error: mkl-service + Intel(R) MKL: MKL_THREADING_LAYER=INTEL is incompatible with libgomp-a34b3233.so.1 library.

### ISSUE THREAD

**Issue by tms2003** [THU-MIG/yolov10#61]
when I try to training the code:
```
yolo detect train data=data/coco11.yaml model=yolov10x.pt epochs=300 batch=32 imgsz=640 device=0,1,2,3

```
the error had happen.
this' error info:
```
Transferred 1123/1135 items from pretrained weights
DDP: debug command /root/miniconda3/envs/py310/bin/python -m torch.distributed.run --nproc_per_node 4 --master_port 37593 /root/.config/Ultralytics/DDP/_temp_65bsxxgj140572035512016.py
Error: mkl-service + Intel(R) MKL: MKL_THREADING_LAYER=INTEL is incompatible with libgomp.so.1 library.
        Try to import numpy first or set the threading layer accordingly. Set MKL_SERVICE_FORCE_INTEL to force it.
Traceback (most recent call last):
  File "/root/miniconda3/envs/py310/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/root/tms/software/yolov10/ultralytics/cfg/__init__.py", line 587, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/root/tms/software/yolov10/ultralytics/engine/model.py", line 657, in train
    self.trainer.train()
  File "/root/tms/software/yolov10/ultralytics/engine/trainer.py", line 208, in train
    raise e
  File "/root/tms/software/yolov10/ultralytics/engine/trainer.py", line 206, in train
    subprocess.run(cmd, check=True)
  File "/root/miniconda3/envs/py310/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/root/miniconda3/envs/py310/bin/python', '-m', 'torch.distributed.run', '--nproc_per_node', '4', '--master_port', '37593', '/root/.config/Ultralytics/DDP/_temp_65bsxxgj140572035512016.py']' returned non-zero exit status 1.
```
so,maybe sth is error.

**Comment by jameslahm** [comment]
Thanks for your interest! Does this issue https://github.com/pytorch/pytorch/issues/37377 help?

**Comment by jameslahm** [comment]
Please feel free to reopen this issue if you have further questions.

**Comment by midasklr** [comment]
export MKL_SERVICE_FORCE_INTEL=TRUE
