### ISSUE TITLE
Meet "freeze_support()" RuntimeError when training yolov10. How can I solve this?

### ISSUE THREAD

**Issue by Twilighthui** [THU-MIG/yolov10#67]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\ProgramData\Anaconda3\envs\pytorch1.13\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "D:\ProgramData\Anaconda3\envs\pytorch1.13\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "D:\ProgramData\Anaconda3\envs\pytorch1.13\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "D:\ProgramData\Anaconda3\envs\pytorch1.13\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "D:\ProgramData\Anaconda3\envs\pytorch1.13\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "D:\ProgramData\Anaconda3\envs\pytorch1.13\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "D:\ProgramData\Anaconda3\envs\pytorch1.13\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "g:\Detect_2024\yolov10-main\train.py", line 11, in <module>
  File "D:\ProgramData\Anaconda3\envs\pytorch1.13\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\ProgramData\Anaconda3\envs\pytorch1.13\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "D:\ProgramData\Anaconda3\envs\pytorch1.13\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "D:\ProgramData\Anaconda3\envs\pytorch1.13\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "D:\ProgramData\Anaconda3\envs\pytorch1.13\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

**Comment by Y-T-G** [comment]
You have to add:
`if __name__ == '__main__':` before your training script.

**Comment by Twilighthui** [comment]
Thanks for the answer. Surprisingly, it's really due to this small problem.

**Comment by quitmeyer** [comment]
> You have to add: `if __name__ == '__main__':` before your training script.

helped me too! thanks!
